name: Auto-merge

on:
  pull_request:
    branches: [master]

jobs:
  auto-merge:
    runs-on: windows-latest
    steps:
      - name: Dependency Merge
        uses: buildsville/simple-merge@v1
        id: merge
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          method: "dependency merge"
          labels: '[ "dependencies" ]'
          title: "Auto Merge"
          message: "Merge dependabot dependencies"
