name: Auto-merge

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  abuild:
    runs-on: windows-latest
    steps:
      - name: Merge
        uses: buildsville/simple-merge@v1
        id: merge
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          method: 'merge'
          labels: '[ "dependencies" ]'
          title: 'Auto Merge'
          message: 'Merge dependabot dependencies'
